# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89bd74eac55048fd320f3ae65ff2a9663efc681a408fd973a80c57d6765d70e9b9e10ffddf512cd509252c4383226898f4083e2cb203a157021410addac6047d

test:
  secret_key_base: 56883f20cf4bd1b4e913f77d156b74772a551f327e464a86c68af4663e0a87a688d8e0870b323adb2892122e08cbb6298702c2a9b67e787270ddd8665a96fe89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
